# Generated by Django 5.2.12 on 2026-04-04 23:03

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    gardeners_group, _ = Group.objects.get_or_create(name='Gardeners')

    gardener_perms = [
        'add_plant', 'change_plant', 'delete_plant', 'view_plant',
        'add_maintenancerecord', 'change_maintenancerecord', 'delete_maintenancerecord', 'view_maintenancerecord',
        'view_notification', 'change_notification',
        'change_gardener', 'view_gardener', 'add_tag'
    ]

    for perm_code in gardener_perms:
        perm = Permission.objects.get(codename=perm_code)
        gardeners_group.permissions.add(perm)

    moderators_group, _ = Group.objects.get_or_create(name='Moderators')

    mod_perms = [
        'add_tag', 'change_tag', 'delete_tag', 'view_tag',
        'view_plant', 'delete_plant',
        'view_maintenancerecord',
        'view_notification'
    ]

    for perm_code in mod_perms:
        perm = Permission.objects.get(codename=perm_code)
        moderators_group.permissions.add(perm)


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
