# Generated by Django 5.2.12 on 2026-04-03 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Watering', 'Watering'), ('Fertilizing', 'Fertilizing'), ('Pruning', 'Pruning'), ('Repotting', 'Repotting'), ('Other', 'Other')], default='Other', max_length=20)),
                ('date', models.DateField(help_text='*When was the care provided?')),
                ('notes', models.TextField(blank=True, help_text='*Optional: e.g., "Added 500ml water" or "Used bio-fertilizer".', null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='plants.plant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
