# Generated by Django 5.2.12 on 2026-03-10 03:30

import django.core.validators
import django.db.models.deletion
import plants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardeners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(error_messages={'unique': 'That tag is already registered!'}, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['tag_name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'The plant name must be at least 5 chars long!'), plants.validators.PlantNameValidator()])),
                ('species', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('city', models.CharField(help_text='The city where the plant is located.', max_length=50)),
                ('address', models.CharField(blank=True, help_text='Optional: Apartment, floor, or specific spot (e.g., "Balcony").', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gardener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='gardeners.gardener')),
                ('tags', models.ManyToManyField(blank=True, related_name='plants', to='plants.tag')),
            ],
            options={
                'ordering': ['plant_name'],
            },
        ),
    ]
