# Generated by Django 5.2.12 on 2026-04-04 17:06

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import plants.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['tag_name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(help_text='*Allowed plant names can contain letters, digits, spaces and hyphens.', max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'The plant name must be at least 3 chars long!'), plants.validators.PlantNameValidator()])),
                ('species', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('city', models.CharField(help_text='*The city where the plant is located.', max_length=50)),
                ('address', models.CharField(blank=True, help_text='*Optional: apartment, floor, or specific spot (e.g., "Balcony").', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('watering_frequency', models.PositiveIntegerField(default=1, help_text='*Share how many times per month the plant needs watering.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('fertilizing_frequency', models.PositiveIntegerField(default=0, help_text='*How many times per year should this plant be fertilized?', validators=[django.core.validators.MaxValueValidator(24)])),
                ('pruning_frequency', models.PositiveIntegerField(default=0, help_text='*How many times per year should this plant be pruned?', validators=[django.core.validators.MaxValueValidator(12)])),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('favourite_by', models.ManyToManyField(blank=True, related_name='favourite_plants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='plants', to='plants.tag')),
            ],
            options={
                'ordering': ['plant_name'],
            },
        ),
    ]
