# Generated by Django 5.2.12 on 2026-03-10 03:40

from django.db import migrations


def create_initial_tags(apps, schema_editor):
    tag_model = apps.get_model('plants', 'Tag')

    tags_to_create = [
        'Indoor', 'Outdoor', 'Tropical', 'Succulent', 'Cactus',
        'Pet Friendly', 'Low Light', 'Bright Light', 'Air Purifying',
        'High Humidity', 'Medicinal', 'Edible', 'Fragrant',
        'Beginner Friendly', 'Hard to Kill', 'Flowering', 'Trailing',
    ]

    for name in tags_to_create:
        tag_model.objects.get_or_create(tag_name=name)


def remove_initial_tags(apps, schema_editor):
    tag_model = apps.get_model('plants', 'Tag')
    tags_to_create = [
        'Indoor', 'Outdoor', 'Tropical', 'Succulent', 'Cactus',
        'Pet Friendly', 'Low Light', 'Bright Light', 'Air Purifying',
        'High Humidity', 'Medicinal', 'Edible', 'Fragrant',
        'Beginner Friendly', 'Hard to Kill', 'Flowering', 'Trailing',
    ]
    tag_model.objects.filter(tag_name__in=tags_to_create).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_tags, reverse_code=remove_initial_tags),
    ]
