# Generated by Django 5.2.12 on 2026-04-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_add_initial_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
