# Generated by Django 5.2.12 on 2026-03-10 04:21

import django.core.validators
import plants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20260310_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='address',
            field=models.CharField(blank=True, help_text='*Optional: apartment, floor, or specific spot (e.g., "Balcony").', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='city',
            field=models.CharField(help_text='*The city where the plant is located.', max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_name',
            field=models.CharField(help_text='*Allowed plant names can contain letters, digits, spaces and hyphens.', max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'The plant name must be at least 5 chars long!'), plants.validators.PlantNameValidator()]),
        ),
    ]
