# Generated by Django 5.2.12 on 2026-03-10 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_plant_address_alter_plant_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='fertilizing_frequency',
            field=models.PositiveIntegerField(default=0, help_text='*How many times per year should this plant be fertilized?', validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='pruning_frequency',
            field=models.PositiveIntegerField(default=0, help_text='*How many times per year should this plant be pruned?', validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering_frequency',
            field=models.PositiveIntegerField(default=1, help_text='*Share how many times per month the plant needs watering.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
