# Generated by Django 5.2.12 on 2026-03-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plant_fertilizing_frequency_plant_pruning_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
