# Generated by Django 5.2.12 on 2026-03-10 02:31

import django.core.validators
import gardeners.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gardener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(error_messages={'unique': 'That nickname is already in use!'}, help_text='*Allowed nicknames can contain only letters and digits.', max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Your nickname must be at least 3 chars long!'), gardeners.validators.LettersDigitsOnlyValidator()])),
                ('first_name', models.CharField(help_text='*Starts with a capital letter. Letters and hyphens only.', max_length=40, validators=[django.core.validators.MinLengthValidator(2, 'Your name must be at least 2 chars long!'), gardeners.validators.FirstAndLastNameValidator()])),
                ('last_name', models.CharField(help_text='*Starts with a capital letter. Letters and hyphens only.', max_length=40, validators=[django.core.validators.MinLengthValidator(2, 'Your name must be at least 2 chars long!'), gardeners.validators.FirstAndLastNameValidator()])),
                ('email', models.EmailField(error_messages={'unique': 'That email is already registered!'}, max_length=40, unique=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('is_pro', models.BooleanField(default=False)),
            ],
        ),
    ]
