# Generated by Django 5.2.12 on 2026-04-03 21:05

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import gardeners.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gardener',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(blank=True, error_messages={'unique': 'That nickname is already in use!'}, help_text='*Allowed nicknames can contain only letters and digits.', max_length=40, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Your nickname must be at least 3 chars long!'), gardeners.validators.LettersDigitsOnlyValidator()])),
                ('first_name', models.CharField(blank=True, help_text='*Starts with a capital letter. Letters and hyphens only.', max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Your name must be at least 2 chars long!'), gardeners.validators.FirstAndLastNameValidator()])),
                ('last_name', models.CharField(blank=True, help_text='*Starts with a capital letter. Letters and hyphens only.', max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Your name must be at least 2 chars long!'), gardeners.validators.FirstAndLastNameValidator()])),
                ('about_me', models.TextField(blank=True, null=True)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_pro', models.BooleanField(default=False)),
            ],
        ),
    ]
