# Generated by Django 5.2.12 on 2026-04-06 13:43

import cloudinary.models
import common.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardeners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardener',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[common.validators.FileSizeValidator(5)], verbose_name='image'),
        ),
    ]
